In [3]:
import pandas as pd
import numpy as np

In [11]:
students=np.random.randint(low=1,high=100,size=[20,])

subjects=np.random.choice(['maths','english','physics','chemistry'],20)

default=np.random.choice([0,1],20)

In [13]:
students

array([36, 14, 54,  1, 40, 74, 51, 85, 40, 75, 23, 19, 83, 92, 63, 37, 76,
       18, 73, 76])

In [15]:
np.sort(students)

array([ 1, 14, 18, 19, 23, 36, 37, 40, 40, 51, 54, 63, 73, 74, 75, 76, 76,
       83, 85, 92])

In [19]:
default

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0])

In [23]:
subjects

array(['chemistry', 'physics', 'chemistry', 'english', 'english',
       'english', 'maths', 'chemistry', 'physics', 'english', 'chemistry',
       'chemistry', 'english', 'chemistry', 'english', 'english',
       'english', 'chemistry', 'chemistry', 'chemistry'], dtype='<U9')

In [25]:
a=[3,4,5]
b=[6,7,8]
c=['a','b','c']
list(zip(a,b,c))

[(3, 6, 'a'), (4, 7, 'b'), (5, 8, 'c')]

In [27]:
mydata=list(zip(students,subjects,default))

In [29]:
mydata

[(36, 'chemistry', 0),
 (14, 'physics', 0),
 (54, 'chemistry', 0),
 (1, 'english', 0),
 (40, 'english', 1),
 (74, 'english', 0),
 (51, 'maths', 0),
 (85, 'chemistry', 0),
 (40, 'physics', 0),
 (75, 'english', 1),
 (23, 'chemistry', 0),
 (19, 'chemistry', 1),
 (83, 'english', 0),
 (92, 'chemistry', 0),
 (63, 'english', 0),
 (37, 'english', 0),
 (76, 'english', 1),
 (18, 'chemistry', 1),
 (73, 'chemistry', 0),
 (76, 'chemistry', 0)]

In [31]:
df=pd.DataFrame(data=mydata,columns=['students','subjects','default'])


In [33]:
df

students   subjects  default
0         36  chemistry        0
1         14    physics        0
2         54  chemistry        0
3          1    english        0
4         40    english        1
5         74    english        0
6         51      maths        0
7         85  chemistry        0
8         40    physics        0
9         75    english        1
10        23  chemistry        0
11        19  chemistry        1
12        83    english        0
13        92  chemistry        0
14        63    english        0
15        37    english        0
16        76    english        1
17        18  chemistry        1
18        73  chemistry        0
19        76  chemistry        0